###########################################################################
#                       make_bet_database.py                              #
# Python script for recursively executing the BET command on a database   #
# of NIFTI files generated by the make_nifti_database.py script. Extracts #
# the brain from the skull on scans for registration purposes.            #
#                                                                         #
# Author: Reece Stevens                                                   #
# Written: March 2015                                                     #
# Last Updated: 6/15/2015                                                 #
###########################################################################

import dicom
import sys
import os
import magic
import subprocess

def main(root_db_dir, output_db_dir):
    # Open /dev/null for tossing stdout
    devnull = open('/dev/null', 'w');
    # Check if the correct permissions exist to write to the output location
    try:
        os.makedirs(output_db_dir);
    except OSError:
        if not os.path.isdir(output_db_dir):
            print ("Unable to create new root directory of database. Are you sure you have permissions and file space?\n");
            return;
    
    # Recursively walk through the database 
    directories = [x[0] for x in os.walk(root_db_dir)];
    root_split_path = root_db_dir.split("/");
    for path in directories:
        split_path = path.split("/");
        # Remove root directory from path
        for x in range (len(root_split_path)):
            split_path.pop(0);
        prefix = "";
        # Build an identical file structure in the output directory
        for folder in split_path:
            try:
                os.makedirs(output_db_dir + "/" + prefix + folder);
                print("Creating directory " + output_db_dir + "/" + prefix + folder + "\n");
            except OSError:
                if not os.path.isdir(output_db_dir + "/" + prefix + folder):
                    print("Unable to create subdirectories.\n");
                    return;
            prefix += (folder + "/");
        
        # Perform extraction on each file in the directory
        dir_files = [f for f in os.listdir(path) if os.path.isfile(os.path.join(path, f))];
        for k in dir_files:
            if (k == ".DS_Store"): # Ignore hidden file
                dir_files.remove(k);
            else:
                # Extract the brain from the scan using BET
                split_name = k.split(".");
                subprocess.call(["/work/03187/rstevens/lonestar/fsl/fsl/bin/bet", (root_db_dir + "/" + prefix + k), (output_db_dir + "/" + prefix + split_name[0]), "-R"], stdout=devnull); 
                print(k + " has been successfully extracted.\n");

# Function handle to allow command line passing of arguments
if __name__ == '__main__':
    try:
        main(sys.argv[1], sys.argv[2]);
    except IndexError:
        print("Not enough arguments.\nUsage: db2nii <source_dir> <output_dir>\n");
