#!/bin/bash
#$ -N stir_registration
#$ -M reecestevens@utexas.edu
#$ -m {e|a}
#$ -V
#$ -o /work/03187/rstevens/registration_output.txt
#$ -j

/home1/03187/rstevens/STIR/bin/db_reg /work/03187/rstevens/bet_output_db /work/03187/rstevens/reg_output
