#!/bin/bash
#$ -N stir_registration
#$ -M reecestevens@utexas.edu
#$ -m bea
#$ -V
#$ -o /work/03187/rstevens/registration_output.txt
#$ -j y
#$ -l h_rt=3:30:00
#$ -q normal
#$ -pe 12way 12

/home1/03187/rstevens/STIR/bin/db_reg /work/03187/rstevens/nifti_output_db /work/03187/rstevens/reg_output_no_skull_extract
